name: Status check functions
on: [push]

jobs:
    job-1:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1
              run: sleep 20
            - name: Step 2
              run: exit 1
            - name: Runs on Success
              if: success()
              run: echo 'Runs on Success'
            - name: Runs on cancelled
              if: failure()
              run: echo 'Runs on cancelled'
            - name: Always runs
              if: always()
              run: echo 'Always runs'
            - name: Run when workflow Cancelled
              if: cancelled()
              run: echo 'Run when workflow cancelled'

    job-2:
        runs-on: ubuntu-latest
        needs: job-1
        if: failure()
        steps:
            - run: echo 'job 2'

