name: First Workflow
on: [push]

jobs:
    run-shell-commands:
        runs-on: ubuntu-latest
        steps:
            - name: echo a string
              run: echo "Hello"
            - name: multiline code
              run:
                npm -v
    parallel-job-run:
        runs-on: macos-latest
        steps:
            - name: install rpm package
              run: brew install rpm
            - name: install tree package
              run: brew install tree
    dependency-job:
        runs-on: windows-latest
        needs: parallel-job-run
        steps:
            - name: checking version
              run: 
                rpm -v
                tree -v

            